### Instalacion
### Buscar recurso para instalacion (Existe)

GET http://127.0.0.1:8000/buscar-recurso?nombre=interfaz-hormolab
Content-Type: application/json
Authorization: Bearer b5c60c71ad91d11573d3333de94be2af3cbdb1492908337040ceeb72722faa0c

### Buscar recurso para instalacion (No existe)

GET http://127.0.0.1:8000/buscar-recurso?nombre=interfaz-hpass
Content-Type: application/json
Authorization: Bearer b5c60c71ad91d11573d3333de94be2af3cbdb1492908337040ceeb72722faa0c

### Descarga de archivos
### Intento de descarga de una aplicacion existente

GET http://127.0.0.1:8000/descargar-archivos-instalacion?nombre=interfaz-hpas&ultimaVersion=1.0.3
Content-Type: application/json
Authorization: Bearer b5c60c71ad91d11573d3333de94be2af3cbdb1492908337040ceeb72722faa0c

### Intento de descarga de una aplicacion inexistente

GET http://127.0.0.1:8000/descargar-archivos-instalacion?nombre=interfaz-hormola&ultimaVersion=1.2.0
Content-Type: application/json
Authorization: Bearer b5c60c71ad91d11573d3333de94be2af3cbdb1492908337040ceeb72722faa0c

### Actualizacion
### Consulta de nuevas versiones (Existe)

GET http://127.0.0.1:8000/buscar-actualizacion?nombre=interfaz-hormolab&version=1.0.2
Content-Type: application/json
Authorization: Bearer b5c60c71ad91d11573d3333de94be2af3cbdb1492908337040ceeb72722faa0c

### Consulta de nuevas versiones (No existe)

GET http://127.0.0.1:8000/buscar-actualizacion?nombre=interfaz-hormolab&version=1.2.0
Content-Type: application/json
Authorization: Bearer b5c60c71ad91d11573d3333de94be2af3cbdb1492908337040ceeb72722faa0c

### Consulta de nueva version (Error)

GET http://127.0.0.1:8000/buscar-actualizacion?nombre=interfaz-hormolab&version=1.2.1
Content-Type: application/json
Authorization: Bearer b5c60c71ad91d11573d3333de94be2af3cbdb1492908337040ceeb72722faa0c

### Consulta de nueva version (Error)

GET http://127.0.0.1:8000/buscar-actualizacion?nombre=interfaz-hormola&version=1.2.0
Content-Type: application/json
Authorization: Bearer b5c60c71ad91d11573d3333de94be2af3cbdb1492908337040ceeb72722faa0c

### Obtener archivo de instrucciones (Existentes)

GET http://127.0.0.1:8000/obtener-instrucciones?nombre=interfaz-hormolab&versionActual=1.0.0&versionActualizable=2.0.0
Content-Type: application/json
Authorization: Bearer b5c60c71ad91d11573d3333de94be2af3cbdb1492908337040ceeb72722faa0c

### Obtener archivo de instrucciones (No existentes)

GET http://127.0.0.1:8000/obtener-instrucciones?nombre=interfaz-hormolab&versionActual=1.0.0&versionActualizable=2.0.5
Content-Type: application/json
Authorization: Bearer b5c60c71ad91d11573d3333de94be2af3cbdb1492908337040ceeb72722faa0c

### Descargar archivo para actualizacion

POST http://127.0.0.1:8000/descargar-archivos
Content-Type: application/json
Authorization: Bearer b5c60c71ad91d11573d3333de94be2af3cbdb1492908337040ceeb72722faa0c

{
  "nombre": "interfaz-hormolab",
  "version": "2.0.0",
  "instrucciones": [
      {
          "elemento": "config.conf",
          "ruta": "bin\/config.conf",
          "accion": "MODIFICAR"
      },
      {
          "elemento": "file1.txt",
          "ruta": "file1.txt",
          "accion": "ELIMINAR"
      }
  ]
}

###
