###

GET http://127.0.0.1:8000/buscar-actualizacion?nombre=interfaz-hormolab&version=1.0.2
Content-Type: application/json
Authorization: Bearer DSFHDSHH73hh2hH7GGhjkhgf5

### Descarga de archivos de instalacion

GET http://127.0.0.1:8000/descargar-archivos-instalacion?nombre=interfaz-hormolab&ultimaVersion=1.2.0

###

GET http://127.0.0.1:8000/obtener-instrucciones?nombre=interfaz-hormolab&ultimaVersion=1.2.0


###
